name: Build Docs
on: [push]
# push:
#   branches: [master]
#   paths:
#     - "docs/**"
#     - "src/**"

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev dependencies
        run: make install-dev

      - name: Build HTML docs
        run: make docs-html

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-site
          path: docs/build/html
          retention-days: 7

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4