name: Build Docs
on: [push]
# push:
#   branches: [master]
#   paths:
#     - "docs/**"
#     - "src/**"

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev dependencies
        run: make install-dev

      - name: Build HTML docs
        run: make docs-html

      - name: Upload docs site
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-site
          path: docs/build/html
          retention-days: 7

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
