name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-3.11-${{ hashFiles('requirements*.txt') }}

      - name: Install dev dependencies
        run: make install-dev

      # --- Code quality ---
      - name: Lint (make lint)
        run: make lint

      - name: Code format (make format)
        run: make format

      - name: Type checking (make type-check)
        run: make type-check

      # --- Tests ---
      - name: Unit tests with coverage
        run: make test-coverage

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/
          retention-days: 7
